version: "3.1"
services:

  backend:
    image: tearust/website-backend:0.6.5
    container_name: tearust-backend
    ports:
      - 3001:3001
    volumes: 
      - ../tapp-tutor:/tapp-tutor
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
      - LAYER1_URL=ws://64.227.57.97:9944
      - LAYER1_ACCOUNT=Alice
    command: "node index.js"
    
  frontend:
    image: tearust/website-frontend:0.6.5
    container_name: tearust-frontend
    volumes:
      - ./frontend/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./frontend/web:/www/dist

    ports:
      - 90:80


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
        
    
