version: "3.1"
services:

  backend:
    image: tearust/website-backend:0.1
    container_name: backend
    ports:
      - 3001:3001
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
    command: "node index.js"
    