version: "3.1"
services:

  backend:
    image: tearust/website-backend:0.2
    container_name: backend
    ports:
      - 3001:3001
    environment: 
      - NODE_ENV=prod
      - SERVER_PORT=3001
    command: "node index.js"
    
  frontend:
    image: tearust/website-frontend:0.2
    container_name: frontend
    ports:
      - 80:80
        
    