version : "3.2"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/letsencrypt:/etc/letsencrypt
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80